version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: codeBoardDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - backend

  app-server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/codeBoardDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - app-server
    networks:
      - frontend

networks:
  backend:
  frontend:
